#
# Gem file set for HelloWorld
# Last Update: 16/Nov/2011
#

source 'http://rubygems.org'

# Core gems
gem 'rails', '3.0.6'
gem 'unicorn'

# Components
gem 'rake'
gem 'sass'
gem 'haml'
gem 'jammit'
gem 'twitter'
gem 'jquery-rails'
gem 'headjs-rails'
gem 'mustache'
gem 'yajl-ruby' #faster json reading
gem 'oauth'
gem 'devise', '1.4.9'
gem 'mysql2', '< 0.3'
gem 'omniauth'
gem 'json'

group :development do
  gem 'barista'
  gem 'coffee-script'
  
  # gem 'ruby-debug' #  for ruby 1.8.7
  # gem 'ruby-debug19', :require => 'ruby-debug' # for ruby 1.9.2+
end
